# CodeDeploy 전용 설정 파일

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app # JAR 파일 복사 위치
    overwrite: yes

permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: stop_application.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start_application.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: ubuntu