version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Build started on `date`
      - java -version
      - echo Downloading and installing Gradle...
      - wget -q https://services.gradle.org/distributions/gradle-8.5-bin.zip
      - unzip -q gradle-8.5-bin.zip
      - export PATH=$PWD/gradle-8.5/bin:$PATH
      - gradle --version

  build:
    commands:
      - echo Building with Gradle...
      - gradle build
#      - gradle clean build test

  # build 가 완료된 후, codeDeploy에 전달할 파일들을 모으는 작업
  # 모은 파일들은 S3에 올려 codeDeploy로 배포
  post_build:
    commands:
      - echo Build completed on `date`
      # 1. 아티팩트를 모을 임시 디렉토리를 생성합니다.
      - DEPLOY_DIR=deploy_artifact
      - mkdir -p $DEPLOY_DIR

      # 2. JAR 파일(빌드 결과물)을 임시 디렉토리로 이동/복사합니다.
      - cp build/libs/*.jar $DEPLOY_DIR/

      # 3. appspec.yml과 스크립트들을 복사합니다.
      - cp appspec.yml $DEPLOY_DIR/
      - cp -r scripts/ $DEPLOY_DIR/

      # 4. 임시 디렉토리의 내용을 확인합니다.
      - ls -la $DEPLOY_DIR

artifacts:
  files:
    - '**/*'
  base-directory: deploy_artifact # 이 폴더 안의 내용만 가져감
  discard-paths: yes