version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Build started on `date`
      - java -version
      - echo Downloading and installing Gradle...
      - wget -q https://services.gradle.org/distributions/gradle-8.5-bin.zip
      - unzip -q gradle-8.5-bin.zip
      - export PATH=$PWD/gradle-8.5/bin:$PATH
      - gradle --version

  build:
    commands:
      - echo Building with Gradle...
      - gradle clean build -x test

  post_build:
    commands:
      - echo Build completed on `date`
      - ls -la build/libs/

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/libs/*.jar
  discard-paths: no