version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Build started on `date`
      - echo Checking Java version...
      - java -version

  build:
    commands:
      - echo Building with Gradle...
      # Gradle 사용 시
      - chmod +x ./gradlew
      - ./gradlew clean build -x test

      # Maven 사용 시는 아래 주석 해제하고 위 Gradle 명령어 주석 처리
      # - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Listing build artifacts...
      - ls -la build/libs/  # Gradle
      # - ls -la target/  # Maven

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/libs/*.jar  # Gradle
    # - target/*.jar  # Maven
  discard-paths: no