version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build phase started..."
  build:
    commands:
      - echo "Starting Gradle build..."
      - chmod +x ./gradlew
      - ./gradlew clean build
artifacts:
  files:
    - build/libs/*.jar
